:concurrency: 30
development:
  :concurrency: 30
  :limits:
    get_all_people_worker: 10
    get_parent_id_worker: 10
    default: 10


production:
  :concurrency: 60
  :limits:
    get_all_people_worker: 40
    get_parent_id_worker: 10
    default: 10
