:concurrency: 50
development:
  :concurrency: 30
  :limits:
    get_all_people_worker: 0
    get_last_people_worker: 20
    get_parent_id_worker: 5
    default: 5
production:
  :concurrency: 50
  :limits:
    get_all_people_worker: 0
    get_last_people_worker: 30
    get_parent_id_worker: 10
    default: 10
