:concurrency: 40
development:
  :concurrency: 40
  :limits:
    get_all_people_worker: 15
    get_parent_id_worker: 15
    default: 15


production:
  :concurrency: 40
  :limits:
    get_all_people_worker: 15
    get_parent_id_worker: 15
    default: 15
